### ISSUE TITLE
many_many and default sort order

### ISSUE THREAD

**Issue by minimalic** [symbiote/silverstripe-gridfieldextensions#138]
I already spent a couple of days trying to write a `onBeforeWrite` function, like the one [in the gridfieldextensions docs](https://github.com/silverstripe-australia/silverstripe-gridfieldextensions/blob/master/docs/en/index.md#orderable-rows), but for `many_many` relation. I tried almost everything and I can't access the `extraFields`… :(
Here is a main part of `SamplePage`s and `SampleObject`s:

```
class SamplePage extends Page {

private static $many_many = array(
    'SampleObjects' => 'SampleObject'
);
public static $many_many_extraFields=array(
    'SampleObjects'=>array(
        'IsActive' => 'Boolean',
        'Sort'=>'Int'
    )
);
```

```
class SampleObject extends DataObject {

public static $belongs_many_many=array(
    'SamplePages'=>'SamplePage'
);
public function getCMSFields() {
    $fields = parent::getCMSFields();
    $fields->addFieldToTab('Root.Main', new ReadonlyField('ManyMany[Sort]','My Order'));
    return $fields;
}
```

Now we need something like this in `SampleObject`:

```
public function onBeforeWrite () {
    if (!$this->ManyMany[Sort]) {
        $this->ManyMany[Sort] = SamplePage::manyManyExtraFieldsForComponent('SampleObject')->max('Sort') + 1;
    }
    parent::onBeforeWrite();
}
```

It seems that `$this->ManyMany[Sort]` **doesn't work**. It only works if you create new Field, like `new ReadonlyField('ManyMany[Sort]','My Order')` in `getCMSFields()`.
So I tried following to write a default value in `Sort` in `onBeforeWrite()` function:

```
$newnum = SampleObject::get()->max('ID') + 1;
if(!$this->ID) {
    $this->setField('ManyMany[Sort]', $newnum);
}
```

It **works** fine.

But we don't want the Object ID as new `Sort`.
How can I **access the related "parent" Page** to get all `Sort`s and pick the highest one with `max('Sort') + 1`?
Or how can I get ALL existing `Sort` `extraFields` to pick the highest?
How do You handle default `many_many` sorting?

**Comment by creativeSynergy** [comment]
hi @minimalic have you found a solution for this? I've got the same problem here.

**Comment by hoodweb** [comment]
I am currently experiencing this aswell

**Comment by MattyBalaam** [comment]
I’m also stuck trying to figure this out.

**Comment by robbieaverill** [comment]
This should be fixed now. We've done a lot of work around sorting lists (has_many, many_many and many many through) lately, if the issue persists please feel free to reopen it.
