### ISSUE TITLE
Changing sort order doesn't update LastEdited timestamp

### ISSUE THREAD

**Issue by andreaslindahl** [symbiote/silverstripe-gridfieldextensions#142]
I'm using GridFieldOrderableRows to sort items in a list. I've noticed that the LastEdited column isn't updated in the database when the sort order changes for an item, or several items, in the list. Is this by design? It sort of messes up my partial caching blocks - which is cached using .max(LastEdited) - since I wan't to clear the cache when the order changes.

**Comment by SilbinaryWolf** [comment]
In the GridFieldOrderableRows::reorderItems function, it uses a direct DB query to update the sort order for speed purposes, as a regular write on the data object is slow.

I've done a Pull Request here to fix this issue:
[https://github.com/silverstripe-australia/silverstripe-gridfieldextensions/pull/143](https://github.com/silverstripe-australia/silverstripe-gridfieldextensions/pull/143)

**Comment by robbieaverill** [comment]
Fixed with #143
