### ISSUE TITLE
Ordering classes that extend another DataObject crashes

### ISSUE THREAD

**Issue by jyrkij** [symbiote/silverstripe-gridfieldextensions#145]
## Required to reproduce
- Class hierarchy:
  
  ```
  DataObject
  └── Link
      └── ImageLink
  ```
- `GridField` containing `ImageLink`
- `GridFieldOrderableRows`
## Error & cause

[Full error here](https://gist.github.com/jyrkij/0e9a118038fd726a058a2d0de029f398). The cause seems to be #143. `LastEdited` isn't part of `ImageLink`'s table but rather `Link`. Therefore this should probably use ORM save as id't handle the tables correctly.

/cc @FinBoWa, @anttihaavikko, @snowstorm0182

**Comment by KINKCreative** [comment]
I have a fix for it available, but don't know how to make a PR or have the community begin QA. Can you help? 

https://github.com/KINKCreative/silverstripe-gridfieldextensions/tree/extended-do-last-edited-fix

**Comment by dhensby** [comment]
fixed by #163
