### ISSUE TITLE
How can the GridField - Actions be moved to the right?

### ISSUE THREAD

**Issue by seppzzz** [symbiote/silverstripe-gridfieldextensions#169]
I am using gridfieldextensions and GridFieldEditableColumns on a GridFieldConfig_RelationEditor.

> How can the GridField - Actions be moved to the right?

[<img src="http://www.till.graphics/silverStripe/grid.png">](http://www.till.graphics/silverStripe/grid.png)

class StaffCatObject extends DataObject

```
    private static $many_many = array(
        'Staffs' => 'Staff'
    );

    private static $many_many_extraFields = array(
        'Staffs' => array(
            'SortOrder' => 'Int'
        ),
    );

    public function getCMSFields() {
        $fields = parent::getCMSFields();

.......

    $GridFieldConfig = GridFieldConfig_RelationEditor::create();
    $GridFieldConfig->removeComponentsByType('GridFieldPaginator');
    $GridFieldConfig->addComponent(new GridFieldPaginator(20));
    $GridFieldConfig->addComponent(new GridFieldEditableColumns());
    $GridFieldConfig->addComponent( new GridFieldDeleteAction());
    $items = $this->Staffs();
    if (class_exists('GridFieldOrderableRows') && !$items instanceof UnsavedRelationList) {
        $GridFieldConfig->addComponent(new GridFieldOrderableRows('SortOrder'));
    }

    $gridfield = new GridField("Staff", $this->StaffCatTitle, $this->Staffs()->sort('SortOrder'), $GridFieldConfig); //->sort('SortOrder')

    $gridfield->getConfig()->getComponentByType('GridFieldEditableColumns')->setDisplayFields(array(

        'Display' => array(
            'callback' => function ($record, $column, $gridfield) {
                    return new CheckboxField('Display');
            },
            'title' => 'Display'
            ),

        'AdImpressum' => array(
            'title' => 'Ad Impressum',
            'field' => 'CheckboxField'
            )
    ));


    $fields->addFieldToTab('Root.Main', $gridfield);

    return $fields;
```

class Staff extends DataObject

```
private static $belongs_many_many = array(
    'StaffCatObjects' => 'StaffCatObject'
);

static $summary_fields = array(
    'Thumbnail' => 'Thumbnail',
    'StaffTitle' => 'Name',
    'Email' => 'Email',
    'CheckDisplay' => 'wird angezeigt in'
);
```

**Comment by tillzzz** [comment]
I've found a very ugly workaround:

`$GridFieldConfig->addComponent(new GridFieldEditableColumns());
		$GridFieldConfig->addComponent(new GridFieldLayoutHelper());`

`<?php
class GridFieldLayoutHelper implements GridField_ColumnProvider {
	
	public function augmentColumns($field, &$cols) {
		
		$key = array_search('Actions', $cols);
		$actions = $cols[$key];
		unset($cols[$key]);
		array_push($cols, $actions);
	}
	
	public function getColumnsHandled($field) {
		return array();
	}
	
	public function getColumnContent($field, $record, $col) {
		
	}
	
	public function getColumnAttributes($field, $record, $col) {
		
	}

	public function getColumnMetadata($gridField, $col) {
		
	}
	
}`

**Comment by robbieaverill** [comment]
Feel free to reopen if you think there's a bug here. At this point is look more like a question.

**Comment by mlewis-everley** [comment]
@robbieaverill I think this is a bug? Since SS4 the gridfield actions no longer appear to the right (they only appear to the left, unlike the default GridField).

So far, the only way to resolve this seems to be to implement the layout handler recommended by @seppzzz ...

**Comment by robbieaverill** [comment]
@mlewis-everley would you mind providing steps to reproduce, affected versions and a clear description of what the problem is please?

**Comment by mlewis-everley** [comment]
OK, a simple example:

```php
class Product extends DataObject
{
    private static $table_name = "Product";

    private static $db = [
        "Name"            => "Varchar",
        "Quantity"    => "Int",
    ];
}

class Order extends DataObject
{
    private static $table_name = "Order";

    private static $db = [
        'Date' => 'Date'
    ];

    private static $many_many = [
        'Products' => Product::class
    ];

    public function getCMSFields()
    {
        $fields = parent::getCMSFields();
        $products_field = $fields->dataFieldByName("Products");

        if ($products_field) {
            // Add quantity field to products
            $new_fields = new GridFieldEditableColumns();
            $new_fields->setDisplayFields(
                [
                    'Title' => [
                        'title' => 'Name',
                        'field' => TextField::class
                    ],
                    'Quantity' => [
                        'title' => 'Quantity',
                        'field' => NumericField::class
                    ]
                ]
            );
    
            $products_field
                ->getConfig()
                ->removeComponentsByType(GridFieldDataColumns::class)
                ->removeComponentsByType(GridFieldAddNewButton::class)
                ->addComponent($new_fields)
        }

        return $fields;
    }
}
```

When I use this code, the actions (edit/delete) in the `Products` gridfield are left aligned.

If I try to remove and re-add the actions then they are still forced to the left.

If I create an instance of the layout helper suggested by @seppzzz  and add it to the gridfield, the actions move to the right.

Does that help?

**Comment by robbieaverill** [comment]
@mlewis-everley yep, thank you!

**Comment by robbieaverill** [comment]
Hi @mlewis-everyley, the fix is to add the component before the edit button:

```php
    ->addComponent($new_fields, GridFieldEditButton::class);
```

I'll update the docs too to make this clearer

**Comment by robbieaverill** [comment]
Here we go: https://github.com/symbiote/silverstripe-gridfieldextensions/commit/856fce1b8c66f7c51c7414c0b73bdfe7f1afbc28

**Comment by mlewis-everley** [comment]
@robbieaverill Cool, I didn't realise `GridFieldConfig::addComponent()` accepts a second parameter!
