### ISSUE TITLE
GridFieldOrderableRows with Sqlite3 fails on reorder

### ISSUE THREAD

**Issue by cloeon** [symbiote/silverstripe-gridfieldextensions#170]
Using SQLite3Database on SS 3.4.1, GridFieldOrderableRows fails on rows 471 and 506 respectively:

`$additionalSQL = (!$list instanceof ManyManyList) ? ', "LastEdited" = NOW()' : '';`

SQLite3 does not support _NOW()_.
Don't know if it is the best solution, but this works instead:

`$additionalSQL = (!$list instanceof ManyManyList) ? ', "LastEdited" = ' . DB::get_conn()->now() : '';`

**Comment by robbieaverill** [comment]
I'm not sure whether this module advertises SQLite compatibility already, but I've triaged this as a feature enhancement and assumed it can be made compatible without breaking any APIs.

**Comment by dhensby** [comment]
fixed by #216
