### ISSUE TITLE
SS4 support

### ISSUE THREAD

**Issue by TheBnl** [symbiote/silverstripe-gridfieldextensions#175]
Hi! 

I'm currently working on a [fork](https://github.com/TheBnl/silverstripe-gridfieldextensions/tree/theb-ss4-bugs) that adds ss4 support to the module, currently i have done some bug and style fixes that make the following features workable: 
- GridFieldEditableColumns
- GridFieldExternalLink
- GridFieldOrderableRows

The following features still require some attention that i'll try to fix in the future
- GridFieldAddNewInlineButton
_there is a issue in the fact that 'tmpl.js' isn't in use anymore_
- GridFieldAddExistingSearchHandler
_i personally have no experience in using this feature so haven't gotten to it jet_
- GridFieldAddNewMultiClass
_there is an conflict between entwine and react in the button, i think, but documentation on react and plans for entwine is still a bit low. And there is an issue in the creation of Objects when they are namespaced. For example when creating a class like `MySite\TestObject` the create action url gets transformed into "/admin/pages/edit/EditForm/field/TestObjects/add-multi-class/**MySite/TestObject**/ItemEditForm" this throws the error that SS cant handle sub-URL's_

In an effort to make my modules SS4 compatible i thought i ought to contribute to the modules that they depend on! Maybe you guys already had some thought on the issues i described above, and can share some pointer in where to look for solving them.

Cheers! 👍

**Comment by TheBnl** [comment]
@jaydenseric @ninty9notout i saw you are also working on SS4 support maybe we could combine efforts?

**Comment by ninty9notout** [comment]
Hey sorry @TheBnl I didn't get the notification. I'm merged majority of my changes into @jaydenseric's repo so I have nothing left save for some minor tweaks. I'll grab a patch file once I get a bit more.

**Comment by robbieaverill** [comment]
Hey @TheBnl @jaydenseric @ninty9notout - now that the master branch is working with SS4, do you have anything extra you might like to put up a pull request for, to contribute to it?

**Comment by jaydenseric** [comment]
@robbieaverill Thanks for asking, but I am pretty out of the loop. I left the PHP ecosystem for Node.js, and don't use Silverstripe anymore. I have put off deleting my remaining [SS4 related forks](https://github.com/jaydenseric?utf8=%E2%9C%93&tab=repositories&q=silverstripe) because some people had them as composer dependencies.

**Comment by TheBnl** [comment]
Hi @robbieaverill, i must say that i haven't gotten around to working on the fork for the past half year. I also didn't have any new features. This issue can probably be closed then! 👍

**Comment by robbieaverill** [comment]
Thanks for al the input!
