### ISSUE TITLE
DropdownFields in inline editing shows keys

### ISSUE THREAD

**Issue by faloude** [symbiote/silverstripe-gridfieldextensions#176]
DropdownField's in the inline editing columns show the *keys* of dropdownfield's array, instead of the *values*.

`DropdownField::create('Type', 'Type', array('A' => 'banana', 'B' => 'orange'));`
will show a <select> field with A and B.

Is this normal behaviour?

**Comment by robbieaverill** [comment]
@faloude can you please provide your SilverStripe and gridfieldextensions versions?

**Comment by faloude** [comment]
@robbieaverill I don't run the installation any longer in which I observed this bug.

I can confirm that this bug does **not** occur in my current environment:
SS 3.6.1 + symbiote\gridfildextensions 1.5

**Comment by robbieaverill** [comment]
Thanks
