### ISSUE TITLE
SS4 GridFieldAddNewMultiClass 'handleAdd' class getter

### ISSUE THREAD

**Issue by jackoconnor21** [symbiote/silverstripe-gridfieldextensions#178]
Currently the `handleAdd` function will take the param 'ClassName' from the passed $request. With SS4 this will just get the vendor from the namespace as opposed to Vendor\Project\Something\Class, meaning anything added with GridFieldAddNewMultiClass will get an error upon creation.

**Comment by tractorcow** [comment]
Also raised at https://github.com/silverstripe/silverstripe-framework/issues/7069.

Suggested fix is to sanitise / desanitise classname for url, or use querystring arg.

**Comment by robbieaverill** [comment]
Looks like this is fixed with #182. Feel free to reopen if it's still a problem.
