### ISSUE TITLE
Regular releases pretty please

### ISSUE THREAD

**Issue by jonom** [symbiote/silverstripe-gridfieldextensions#181]
Last release is more than 6 months old, so bug fixes like [this one](https://github.com/silverstripe-australia/silverstripe-gridfieldextensions/pull/163) haven't made it in to a stable release yet which makes composer updates difficult.

Would be great to see a new release tag after every PR to a stable branch.

Thanks!

**Comment by kinglozzer** [comment]
Bump 🤜💨

**Comment by jonom** [comment]
If you exclude CMS this appears to be the [#1 most popular SilverStripe module](http://addons.silverstripe.org/add-ons) so a lot of people would appreciate this 😁

**Comment by robbieaverill** [comment]
They seem pretty regular now :)
