### ISSUE TITLE
Possible to use module in ModelAdmin?

### ISSUE THREAD

**Issue by JustinTBrown** [symbiote/silverstripe-gridfieldextensions#191]
Attempting to add components from this module generates the following error:

`Fatal error: Class 'GridFieldAddExistingSearchButton' not found in /PROJECT_PATH/mysite/code/admin/ArtistAdmin.php on line 21`

Here's the `getEditForm` portion of my ModelAdmin:

```
public function getEditForm($id = null, $fields = null) {
    $form = parent::getEditForm($id, $fields);
    $gridFieldName = $this->sanitiseClassName($this->modelClass);
    $gridField = $form->Fields()->fieldByName($gridFieldName);
    $gridField->getConfig()->addComponent(new GridFieldAddExistingSearchButton());
    return $form;
  }
```

Is it possible to use this module in ModelAdmin or am I barking up the wrong tree?

**Comment by robbieaverill** [comment]
Did you `?flush=1` the browser? What you've shown should work fine.

**Comment by JustinTBrown** [comment]
Wowwww. OF COURSE. Many thanks, that was it.

Follow-up question: Can editable columns be used in ModelAdmin? Inline edits do not appear to save after entry or tabbing, and ModelAdmin of course doesn't provide a save function, so it's not immediately clear to me how to get this to work.

**Comment by robbieaverill** [comment]
@JustinTBrown yeah - you'd need to add the necessary GridField components in your ModelAdmin's `getEditForm`, it should work the same as any other GridField. If you continue to have trouble with this, please feel free to reopen this issue.
