### ISSUE TITLE
Upgrade CWP 1.4.1 to 1.5.x

### ISSUE THREAD

**Issue by thinkingcap** [symbiote/silverstripe-gridfieldextensions#192]
Is there a work around for this?
`[Composer\DependencyResolver\SolverProblemsException]
    Problem 1
      - Installation request for cwp/cwp-recipe-basic ~1.5.2@stable -> satisfiable by cwp/cwp-recipe-basic[1.5.2].
      - cwp/cwp-recipe-basic 1.5.2 requires silverstripe-australia/gridfieldextensions 1.4.2@stable -> no matching package found.`

**Comment by robbieaverill** [comment]
Hey @thinkingcap - strange issue - [there is a 1.4.2 release](https://github.com/silverstripe-australia/silverstripe-gridfieldextensions/releases/tag/1.4.2). Have you tried it again since?

**Comment by robbieaverill** [comment]
Did you get this resolved @thinkingcap?

**Comment by dhensby** [comment]
please re-open if this issue persists.
