### ISSUE TITLE
Namespacing update hasn't updated the template directory, so all templates break with

### ISSUE THREAD

**Issue by pitchandtone** [symbiote/silverstripe-gridfieldextensions#195]
None of the following templates could be found: Symbiote\GridFieldExtensions\GridFieldOrderableRowsDragHandle in themes "Array ( [0] => silverstripe/admin:cms-forms [1] => $default ) "

**Comment by pitchandtone** [comment]
Should be as easy as renaming the folder

**Comment by colymba** [comment]
👍

**Comment by nglasl** [comment]
This should now be fixed in the latest release, but please let us know if the issue persists.
