### ISSUE TITLE
A function in GridfieldExtensions.js is making unselectable the items in other gridfields

### ISSUE THREAD

**Issue by MarcioBarrientos** [symbiote/silverstripe-gridfieldextensions#222]
I found that this function is making unselectable the items in other gridfields without gridfields extensions after I enter to a page using gridfieldextensions 

`
$('.grid-field .ss-gridfield-item').entwine({
			onclick: function(e) {
				// Prevent the default row click action when clicking a cell that contains a field
				if (this.find('.editable-column-field').length) {
					e.stopPropagation();
				}
			}
		});
`

To replicate this issue I use Lumberjack to have a gridfield of pages, then each child pages have a gridfield with gridfieldorderablerows component.
When I navegate back to parent page the lumberjack is not selectable anymore.

I made a quick fix adding an extra class to gridfield with any gridfieldextensions component, then editing the GridfieldExtensions.js to use that class:

`$('.grid-field.ss-gridfield-extensions .ss-gridfield-item' ).entwine({....`

**Comment by robbieaverill** [comment]
Thanks for reporting @MarcioBarrientos - could you please provide the version of SilverStripe and gridfieldextensions you're using?

**Comment by MarcioBarrientos** [comment]
Hi @robbieaverill I'm using Silverstripe 4.0.0-rc3 with GridfieldExtensions 3.0.x-dev (latest build)

**Comment by zanderwar** [comment]
I'm using the same as @MarcioBarrientos, @robbieaverill see reference above which may be closable now to this discovery

**Comment by robbieaverill** [comment]
Sounds like it could be a handler binding problem

**Comment by robbieaverill** [comment]
@MarcioBarrientos @zanderwar does https://github.com/symbiote/silverstripe-gridfieldextensions/pull/235 fix this issue?

**Comment by MarcioBarrientos** [comment]
@zanderwar Yes, #235 fix the issue with the gridfield items.
