### ISSUE TITLE
Possible bug: Adding new multi class item then saving it triggers change tracker to confirm

### ISSUE THREAD

**Issue by robbieaverill** [symbiote/silverstripe-gridfieldextensions#226]
This was raised in https://github.com/dnadesign/silverstripe-elemental/issues/142 and fixed in that module with https://github.com/dnadesign/silverstripe-elemental/pull/149

If you use the add new multi class component, create a new item (which takes you to the edit form) then save it you get an "are you sure..." confirm popup.

The fix in elemental could also be applied to this module, assuming this issue occurs in this module on its own.

cc @mfendeksilverstripe

---

If this isn't an issue here we can simply close.

**Comment by mfendeksilverstripe** [comment]
@robbieaverill I created a follow up pull request for the source module:

https://github.com/silverstripe/silverstripe-framework/pull/7591

**Comment by robbieaverill** [comment]
Nice!

**Comment by robbieaverill** [comment]
Closing under the assumption that this will be fixed in core at some stage, rather than gridfieldextensions - feel free to reopen if I've misunderstood
