### ISSUE TITLE
BUG GridFieldConfigurablePaginator styles need to be updated

### ISSUE THREAD

**Issue by robbieaverill** [symbiote/silverstripe-gridfieldextensions#227]
Perhaps the GridFieldPaginator base styles have changed, but we need to update the configurable paginator styles now:

![image](https://user-images.githubusercontent.com/5170590/32703701-71f55baa-c85e-11e7-91ef-fd525753a2be.png)

**Comment by robbieaverill** [comment]
I've got a fix branch ready, will push it and rebase once #225 is merged since it's easier with the assets separated in webpack

**Comment by dhensby** [comment]
@robbieaverill #225 has been closed for now...

**Comment by robbieaverill** [comment]
Yeah, damn. I'll update it

**Comment by robbieaverill** [comment]
PR at #231, I've removed the webpack dependency and well log that as a separate enhancement issue
