### ISSUE TITLE
GridFieldAddNewMultiClass button is halfway off the screen

### ISSUE THREAD

**Issue by dljoseph** [symbiote/silverstripe-gridfieldextensions#229]
At the time of writing, this only happens on the dev-master branch.
```composer require symbiote/silverstripe-gridfieldextensions dev-master```

Screenshot
![screen-shot-for-github-issue](https://user-images.githubusercontent.com/2602860/33071694-77a4a626-ceb4-11e7-8632-96d39af57a5c.png)

Files to reproduce
[mysite-code.zip](https://github.com/symbiote/silverstripe-gridfieldextensions/files/1491222/mysite-code.zip)

**Comment by robbieaverill** [comment]
Reproduced using your example code @dljoseph - thanks

**Comment by robbieaverill** [comment]
Fix at https://github.com/symbiote/silverstripe-gridfieldextensions/pull/240
