### ISSUE TITLE
new v3 release

### ISSUE THREAD

**Issue by ivoba** [symbiote/silverstripe-gridfieldextensions#236]
Can you make a new release with latest fixes?
current stable release 3.0.2 has errors (like wrong jquery ui sprite path) and to get it working you need `3.0.x-dev` version.

**Comment by dhensby** [comment]
If you bump your PHP requirement up to ^3.0.3 then you'll be able to pull in the latest dev branch and then lock on to stable releases once it's published

**Comment by robbieaverill** [comment]
Here we go: https://github.com/symbiote/silverstripe-gridfieldextensions/releases/tag/3.1.0
