### ISSUE TITLE
Invalid SQL query when reordering items via GridFieldOrderableRows for the first time

### ISSUE THREAD

**Issue by michalkleiner** [symbiote/silverstripe-gridfieldextensions#241]
The problem is in https://github.com/symbiote/silverstripe-gridfieldextensions/blob/master/src/GridFieldOrderableRows.php#L564

The $baseTable is not correctly derived from the list (using the name of the db table as the input) and therefore it assumes the table holding the Sort column also holds the LastEdited column (which is then offending in the SQL).

This can be replicated by installing standard SilverStripe CMS recipe, adding "dnadesign/silverstripe-elemental": "2.x-dev", "dynamic/silverstripe-elemental-blocks": "dev-master" and creating and reordering Accordion Panels inside the Accordion block.

It only happens for the first time when the records don't have any Sort value assigned.

**Comment by mak001** [comment]
bump

**Comment by dhensby** [comment]
@michalkleiner @mak001 either of you want to create a PR?

**Comment by michalkleiner** [comment]
I may have some time as we will potentially need it for the coming project.

**Comment by robbieaverill** [comment]
@nightjar has done some work recently for supporting many many through lists in reordering, I wonder whether his changes in #260 might fix this

**Comment by NightJar** [comment]
It depends on versioning status. If models being ordered are versioned the component uses the ORM - I imagine that in this case things _should_ be safe (completely unverified; thinking out loud).

However if items are not versioned, and are not `many_many` _through_, then a manual SQLUpdate call is generated for each row. This would be the code executed to cause the description of the issue in the OP, and I don't _think_ anything I've done will have affected this.

Still, could we worth trying @michalkleiner :) Never hurts to get an extra set of eyes on a PR anyway :P

**Comment by robbieaverill** [comment]
We've done a bunch of work on reordering with this component lately, including with around many many through lists and getting the correct sort column in these and has many lists. If the issue persists, feel free to reopen this issue.

**Comment by NightJar** [comment]
I think this is still valid. I'll leave it closed, but have assigned myself as a reminder to check.
