### ISSUE TITLE
GridFieldOrderableRows issue when data class is Versioned and relation is has_many.

### ISSUE THREAD

**Issue by priyashantha** [symbiote/silverstripe-gridfieldextensions#242]
When the data class is Versioned and you re-order the records and publish it doesn't update the _Live table but only the stage table.

This happens because the condition in this line https://github.com/symbiote/silverstripe-gridfieldextensions/blob/master/src/GridFieldOrderableRows.php#L509 won't be true when the `$table_name` config is defined in the class. `$class` is FQN but `$this->getSortTable($list)` is just the table name.

**Comment by priyashantha** [comment]
Fix added in PR https://github.com/symbiote/silverstripe-gridfieldextensions/pull/243

**Comment by dhensby** [comment]
fixed with #243
