### ISSUE TITLE
Backport versioned orderable rows fix

### ISSUE THREAD

**Issue by NightJar** [symbiote/silverstripe-gridfieldextensions#245]
https://github.com/symbiote/silverstripe-gridfieldextensions/pull/243 fixed an issue with SilverStripe 4's updated Versioned API and publishing changes to re-ordered rows, however the current `master` branch is for the `4.x` release line, and the bug is still present in the `3.x` release line. The fix is somewhat trivial, and needs to be backported to prevent issues arising within other modules which rely on this functionality (and have a requirement of e.g. `^3` - e.g. https://github.com/dnadesign/silverstripe-elemental/issues/177).

**Comment by robbieaverill** [comment]
Released as 3.1.1: https://github.com/symbiote/silverstripe-gridfieldextensions/releases/tag/3.1.1
