### ISSUE TITLE
2.x branches need to be merged up to 3.x branches

### ISSUE THREAD

**Issue by robbieaverill** [symbiote/silverstripe-gridfieldextensions#247]
Note mostly to self, it hasn't been done in a while and there's a lot of conflicts. Need to merge up `2` into `3.0` then on

**Comment by dhensby** [comment]
done

I didn't merge 2 -> 3.0, just 2 -> 3 and 2.0 -> 3.0 (and up) because 2 -> 3.0 would be potentially new APIs going into a patch branch

**Comment by robbieaverill** [comment]
Good point, I hadn't thought about breaking changes between major merging up to patch!
