### ISSUE TITLE
GridFieldAddNewMultiClass handling add requests in SS 4

### ISSUE THREAD

**Issue by simonwinter** [symbiote/silverstripe-gridfieldextensions#249]
When I attempt to use the GridFieldAddNewMultiClass in SilverStripe 4, the URL handler is url encoding the class name, so I end up getting a 400 error.

I add the classes I need like so:

```php
$multiClasses = new GridFieldAddNewMultiClass();
$multiClasses->setClasses([
    ImageMedia::class => 'Image',
    SWFMedia::class   => 'SWF',
    VimeoMedia::class => 'Vimeo'
]);
```

The add action url looks like so:

http://localhost:8089/admin/pages/edit/EditForm/161/field/Media/add-multi-class/Base%5CModel%5CMedia%5CImageMedia

So, to the Handler, this doesn't match the key like:

Base\Model\Media\ImageMedia

What am I doing wrong here?

**Comment by robbieaverill** [comment]
Hey @simonwinter, which version of SilverStripe and gridfieldextensions are you using please

**Comment by simonwinter** [comment]
Hi @robbieaverill ... I was using 3.0.2 of gridfield extensions - that was the problem! Thanks for pointing me in the right direction!
