### ISSUE TITLE
SS4.1.0 BUG: GridFieldOrderableRows no AJAX js loading, wrong AJAX processing

### ISSUE THREAD

**Issue by a2nt** [symbiote/silverstripe-gridfieldextensions#257]
I have created SS-CMS issue report here about loading JS using AJAX headers which doesn't work: https://github.com/silverstripe/silverstripe-cms/issues/2156

But there's an other issue:
To fix previous one I have tried to pre-load GridFieldExtensions JS+CSS using this config as temporary fix:
```
SilverStripe\Admin\LeftAndMain:
  extra_requirements_javascript:
    - 'symbiote/silverstripe-gridfieldextensions:javascript/GridFieldExtensions.js'
    - 'symbiote/silverstripe-gridfieldextensions:javascript/tmpl.js'
  extra_requirements_css:
    - 'symbiote/silverstripe-gridfieldextensions:css/GridFieldExtensions.css'
```

Extension assets were loaded when I have opened: /admin
So I have browsed to a specific page using tree view and re-ordered items:
1) I have noticed an AJAX request using chrome dev-tools and loading spinner appeared
2) I have noticed a message "Records reordered."
3) CMS kept blocked by loading spinner

So I have opened GridFieldExtensions.js, found a line $(".ss-gridfield-orderable tbody").entwine({
and form.addClass('loading'); inside it
Just before adding loading class I have created alert('Loading') and it works ok
Then there goes $.ajax request to check if it works I have created another alert('Success') inside success function and it doesn't works.

As temporary fix I have created done function
```
$.ajax(....).done(function(){
  self.trigger('reload', self);
  form.removeClass('loading');
});
```
It works now, but it's just temporary fix.
Guess both bugs are connected and maybe it's just SS4.1.0 bug cuz actually it looks ok on your side

**Comment by robbieaverill** [comment]
Hi @a2nt 

I can't reproduce with CWP 2.0.0-rc3, which includes:

* SilverStripe core 4.1.0
* silverstripe/userforms 5.1.0
* symbiote/silverstripe-gridfieldextensions 3.1.1

I'm testing GridFieldOrderableRows via the "Form Fields" tab for a user defined form page, which uses it to reorder the form fields.

When I drag and drop records I see a loading spinner which goes away after the AJAX has finished processing.

Can you pease provide a working example so I can replicate this issue?

**Comment by a2nt** [comment]
@robbieaverill looks like the issue comes from colymba/gridfield-bulk-editing-tools 3.0.0-beta4

Causes the issue:
```
public function getCMSFields()
    {
        $fields = parent::getCMSFields();

        $conf = GridFieldConfig_RelationEditor::create(50);
        $conf->addComponent(new GridFieldOrderableRows('SortOrder'));
        $conf->removeComponentsByType('GridFieldDeleteAction');
        $conf->addComponent(new BulkUploader());
        $conf->addComponent(new BulkManager());
        $conf->getComponentByType('Colymba\\BulkUpload\\BulkUploader')->setAutoPublishDataObject(true);

        $fields->addFieldToTab('Root.GalleryImages', GridField::create('GalleryImages', 'GalleryImages', $this->GalleryImages(), $conf));

        return $fields;
    }
}
```

Works ok:
```
public function getCMSFields()
    {
        $fields = parent::getCMSFields();

        $conf = GridFieldConfig_RelationEditor::create(50);
        $conf->addComponent(new GridFieldOrderableRows('SortOrder'));
        $conf->removeComponentsByType('GridFieldDeleteAction');

        $fields->addFieldToTab('Root.GalleryImages', GridField::create('GalleryImages', 'GalleryImages', $this->GalleryImages(), $conf));

        return $fields;
    }
}
```

**Comment by ScopeyNZ** [comment]
@a2nt I have not been able to reproduce this, even using the `colymba/gridfield-bulk-editing-tools` module. I suspect it might be related #246. Are you still able to reproduce this issue?

**Comment by robbieaverill** [comment]
@ScopeyNZ FYI if this issue is related to https://github.com/silverstripe/cwp/issues/141 then I couldn't reproduce this locally, only on CWP. Not sure why.
