### ISSUE TITLE
Many Many Through sort column value after reorder with Page object

### ISSUE THREAD

**Issue by mfendeksilverstripe** [symbiote/silverstripe-gridfieldextensions#268]
Module version: `3.2.0`

### Testing setup:

`ParentObject` has a many many through relationship to `Page` via `RelationObject`.

`Sort` column is defined on `RelationObject` and also on `Page` (inherited from `SiteTree`).

### Issue

`ParentObject` has a gridfield which is used to manage the MMT relationship. Add a bunch of pages to the relation and re-order them. This will work but the `Sort` value will not be as expected.

Normally, the `Sort` value starts from `1` and as you add items it increments (`2`, `3`...). The next value should be computed as a `max` from all the items in the relation. This is how it's working currently in most cases, but not this one. The difference is that the `Sort` column is defined in both `Page` and `RelationObject` and the next value is based on the value form `Page`.`Sort` instead of `RelationObject`.`Sort`.

Renaming the `RelationObject`.`Sort` to something else like `RelationObject`.`MMTSort` will restore expected behaviour.

As far as I can see, this issue is not breaking any functionality. Even if the values are incorrect, they can still be used for sorting.

The concern is that two separate columns are getting mixed up and I don't think relying on unique sort column names is a good idea. I recommend further investigation.

One option would be to not use the MMT list, but using `RelationObject` `DataList` instead when working with sort values.

## Pull requests

- [x] https://github.com/symbiote/silverstripe-gridfieldextensions/pull/272

**Comment by NightJar** [comment]
@mfendeksilverstripe are you able to tell me please if you have also defined the `many_many_extraFields = ['Sort' => 'Int'];` on whichever or the two objects defines the relationship? (`Page` or `ParentObject`... or both?)

**Comment by mfendeksilverstripe** [comment]
We don't use `many_many_extraFields `. `Sort` column is defined on both `RelationObject` and `Page` (via `SiteTree`). Code below illustrates the testing setup, note that all mentioned objects are versioned.

```
class ParentObject extends DataObject
{
    /**
     * @var array
     */
    private static $many_many = [
        'Pages' => [
            'through' => RelationObject::class,
            'from' => 'Parent',
            'to' => 'Page',
        ],
    ];
```

```
class RelationObject extends DataObject
{
    /**
     * @var array
     */
    private static $has_one = [
        'Parent' => ParentObject::class,
        'Page' => Page::class,
    ];

    /**
     * @var array
     */
    private static $db = [
        'Sort' => 'Int',
    ];
```

```
class Page extends SiteTree
{
```

```
class SiteTree extends DataObject
{
    private static $db = array(
     .
     .
     .
        "Sort" => "Int",
     .
     .
     .
    );
```

Let me know if you need more information ;-)

**Comment by mfendeksilverstripe** [comment]
@NightJar `many_many_extraFields` is used to configure completely different data structure so using it should not affect current testing setup.

**Comment by rupachup** [comment]
@brynwhyman this is high priority for TNZ

**Comment by robbieaverill** [comment]
I'm reducing the impact rating because "As far as I can see, this issue is not breaking any functionality"

**Comment by robbieaverill** [comment]
Ok I think I can reproduce this. Here's the code: https://gist.github.com/robbieaverill/f52e0f3ab7b35c0cf7d72a9736970c30

Steps:

* Create three GFE 268 Pages, name them Page 1, Page 2 and Page 3
* Go to the Parent Objects model admin
* Add a Parent Object
* Link the three existing pages to the Parent Object (via autocompleter)
* Check Temp_RelationObject table in the DB -> all Sort values are zero
* Drag Page 1 from the start to the end of the GridField
* Check Temp_RelationObject table in the DB -> Sort values again

Expected: Sort is 3, 1, 2
Actual: Sort is 11, 9, 10

So while the sort values are wrong (they're incrementing from the highest SiteTree value, not themselves), they're correctly relative to each other and @mfendeksilverstripe is right in that this won't cause any problems even though it's wrong.

I'll have a quick look and see if I can patch this but I'm not sure that this would actually cause any problems.

**Comment by robbieaverill** [comment]
PR at https://github.com/symbiote/silverstripe-gridfieldextensions/pull/272

**Comment by NightJar** [comment]
Ideal, thanks @robbieaverill
