### ISSUE TITLE
[SS 4.3] Input group markup is out, select field has border radius

### ISSUE THREAD

**Issue by robbieaverill** [symbiote/silverstripe-gridfieldextensions#269]
Versions:

* silverstripe/cms 4.3.x-dev
* symbiote/silverstripe-gridfieldextensions 3.2.0
* dnadesign/silverstripe-elemental 4.x-dev

The input group for the "add new multi class" component probably has incorrect markup structure. This could be different between Bootstrap 4 beta and stable (SS 4.0/1 and SS 4.2).

![image](https://user-images.githubusercontent.com/5170590/44637879-f2373f00-aa07-11e8-824c-d7ada7e18e39.png)

It shouldn't have border radius on the RHS of the select box

**Comment by ScopeyNZ** [comment]
This is related to chrome not allowing you to change the borders on selects any more (without losing the arrows) - A bootstrap update will fix this as they've done some magic with an svg for the arrow icon in a later version.

**Comment by ScopeyNZ** [comment]
Oh my mistake. I thought that wasn't available and did not realise it was controlled by an additional class (`custom-select`).

**Comment by robbieaverill** [comment]
My mistake, the inputs I'm looking at are part of the elemental module. If this issue occurs in the PHP GridField component, the solution is above
