### ISSUE TITLE
Composer replace does not seem to be replacing the package correctly

### ISSUE THREAD

**Issue by TheBnl** [symbiote/silverstripe-gridfieldextensions#271]
I don't know if there is anything you can do about this since the replace tag seems to be correctly configured in your composer.json. But i will post this here, maybe you've or someone has encountered the same issue. 

I have a couple of dependencies, one of them is `symbiote/silverstripe-gridfieldextensions`. But one of the other packages that i have installed is requiring the old `"silverstripe-australia/gridfieldextensions": "~1.0"`. Should not be a problem because of the replace setting.

Requireing the following package in my composer
```json
"symbiote/silverstripe-gridfieldextensions": "~1.0"
```

But when i'm updating my packages i get the following output:
```bash
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 2 updates, 0 removals
  - Updating symbiote/silverstripe-gridfieldextensions (1.4.4 => 1.5.1): Loading from cache
  - Updating silverstripe-australia/gridfieldextensions (1.4.3 => 1.4.4): Loading from cache
Writing lock file
Generating autoload files
```

Requireing the following package in my composer:
```json
"symbiote/silverstripe-gridfieldextensions": "1.4.4"
```
Output:
```bash
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 2 updates, 0 removals
  - Downgrading symbiote/silverstripe-gridfieldextensions (1.5.1 => 1.4.4): Loading from cache
  - Downgrading silverstripe-australia/gridfieldextensions (1.4.4 => 1.4.3): Loading from cache
Writing lock file
Generating autoload files
```
Requireing the following package in my composer:
```json
"symbiote/silverstripe-gridfieldextensions": "*"
```

Output:
```bash
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 2 updates, 0 removals
  - Updating symbiote/silverstripe-gridfieldextensions (1.4.4 => 1.5.1): Loading from cache
  - Updating silverstripe-australia/gridfieldextensions (1.4.3 => 1.4.4): Loading from cache
Writing lock file
Generating autoload files
```

As you can see the packages seem to dance around each other.

The package the is requiring the old package is `silvershop/shipping`. My solution now is to fork that package and fix the requirements. But this is of course not a real solution.

**Comment by robbieaverill** [comment]
I think the only real proactive fix is to update the package name in the libraries that still use the old one

**Comment by TheBnl** [comment]
Thanks for looking into this!

Yes i've updated that package but there are others that still have the requirement like `silvershop/stock`.

The problem i'm facing is that the build system on the server cannot complete the install progress because it can't run composer install. It returns:
```bash
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for bramdeleeuw/silverstripe-pageslices 1.1.9 -> satisfiable by bramdeleeuw/silverstripe-pageslices[1.1.9].
    - Conclusion: remove silverstripe-australia/gridfieldextensions 1.4.4
    - bramdeleeuw/silverstripe-pageslices 1.1.9 requires symbiote/silverstripe-gridfieldextensions * -> satisfiable by symbiote/silverstripe-gridfieldextensions[1.5.1].
    - don't install silverstripe-australia/gridfieldextensions 1.4.4|remove symbiote/silverstripe-gridfieldextensions 1.5.1
    - don't install symbiote/silverstripe-gridfieldextensions 1.5.1|don't install silverstripe-australia/gridfieldextensions 1.4.4
    - Installation request for silverstripe-australia/gridfieldextensions 1.4.4 -> satisfiable by silverstripe-australia/gridfieldextensions[1.4.4].
```

**Comment by robbieaverill** [comment]
What a mess.

**Comment by TheBnl** [comment]
haha yup, but the weird thing is that normally the replace would work fine, hence the question. 
Now the `silverstripe-australia/gridfieldextensions` is installed form somewhere (can't find it on github anymore) and because it is added second after `symbiote/silverstripe-gridfieldextensions` it overwrites the folder.

**Comment by robbieaverill** [comment]
`silverstripe-australia/gridfieldextensions` is the package name in 1.x, `symbiote/silverstripe-gridfieldextensions` is the package name in 2.x (same code, just re-aliased).

Your example step of requiring `"symbiote/silverstripe-gridfieldextensions": "1.4.4"` should be using the silverstripe-australia name since it's in the 1.x release line

**Comment by robbieaverill** [comment]
@TheBnl let me know if that resolves your problem. I don't think there's anything actionable here so I'm going to close the issue, feel free to reopen if you want to though.

**Comment by TheBnl** [comment]
Yes, you can close, i needed to fork the repo with the old dependency though.
