### ISSUE TITLE
$grid->getManipulatedList() not returning all records and order is messed

### ISSUE THREAD

**Issue by arbalet** [symbiote/silverstripe-gridfieldextensions#275]
on handleMoveToPage $grid->getManipulatedList() is returning only the records that are visible on the page and in this case when you have more pages it scramble the ordering.
Example.

If you have 28 records and you move something from page 1 to page 2 and you have 15 items per page
first 15 records in the db get order from 1 to 15. If you go after that to second page and move something from page 2 to 1 the records that are visible will be ordered from 1 to 15. In this case you will have records that are having the same sequence.

**Comment by robbieaverill** [comment]
Hi @arbalet, can you please provide the versions of SilverStripe and gridfieldextension that you're using?

**Comment by robbieaverill** [comment]
Hi @arbalet, please feel free to reopen this issue with the necessary supporting information. Thanks for raising the issue.
