### ISSUE TITLE
"ManyManyThrough cannot mismatch Versioning between join class and related class"

### ISSUE THREAD

**Issue by kinglozzer** [symbiote/silverstripe-gridfieldextensions#282]
https://github.com/symbiote/silverstripe-gridfieldextensions/blob/3.2.1/src/GridFieldOrderableRows.php#L604-L609, introduced in https://github.com/symbiote/silverstripe-gridfieldextensions/pull/260

I don’t see any reason for this exception to exist - if we’re dealing with an MMTL, we’re updating the sort on the join record and not touching the related record at all. Whether the related record is versioned or not doesn’t matter here, as we’re not inspecting or updating it. If I remove the exception, everything works as expected.

cc @NightJar, do you remember why this was added? 😁

**Comment by kinglozzer** [comment]
I’ve prepared PR https://github.com/symbiote/silverstripe-gridfieldextensions/pull/283 for when you get the chance :D

**Comment by NightJar** [comment]
Cool, I'll look later too.

Long story short is that I believe it'll be to do with user expectations, rather than what is actually possible.
