### ISSUE TITLE
GridFieldAddExistingSearchButton errors on UnsavedRelationList

### ISSUE THREAD

**Issue by lerni** [symbiote/silverstripe-gridfieldextensions#288]
`GridFieldAddExistingSearchButton` throws an error if the DO which holds the GF is not saved.
```[Emergency] Uncaught TypeError: Argument 1 passed to SilverStripe\ORM\DataList::subtract() must be an instance of SilverStripe\ORM\DataList, instance of SilverStripe\ORM\UnsavedRelationList given, called in /.../vendor/symbiote/silverstripe-gridfieldextensions/src/GridFieldAddExistingSearchHandler.php on line 111```

`GridFieldOrderableRows` has a similar issue. https://github.com/symbiote/silverstripe-gridfieldextensions/issues/113

Usually I wrap it in a `if ($this->isInDB()) {...}` but I wonder if there's a better solution? This happens with symbiote/silverstripe-gridfieldextensions  3.2.1

**Comment by robbieaverill** [comment]
Yeah you can't manage relations on an object that isn't saved yet, so your suggested workaround is the correct way to handle this 👍
