### ISSUE TITLE
GridFieldOrderableRows doesn't support polymorphic ManyManyThroughList

### ISSUE THREAD

**Issue by normann** [symbiote/silverstripe-gridfieldextensions#295]
When a 'from' of a many_many relation is polymorphic, and the relation is managed to use a ManyManyThroughList, like the following codes:

```
/**
 * Data extension class, that could be applied to any DataObject as the OwnerObject
 */
class GenericTaggingDataExtension extends DataExtension
{
    private static $many_many = [
        "Tags" => [
            'through' => TagMapping::class,
            'from' => 'OwnerObject',
            'to' => 'JointObject',
        ]
    ];

    public function updateCMSFields(FieldList $fields)
    {
        $fields->dataFieldByName('Tags')->getConfig()
            ->addComponent(GridFieldOrderableRows::create('Sort'));
    }
}

/**
 *The 'through' class, the mapping between DataObject to Tag
 */
class TagMapping extends DataObject
{
    private static $db = [
        'Sort'  => 'Int',
    ];

    private static $has_one = [
        'OwnerObject' => DataObject::class, //Polymorphic has_one
        'JointObject'  => Tag::class,
    ];

    private static $default_sort = '"Sort" ASC';
}

/**
 * The Tag class, the object being joint
 */
class Tag extends DataObject
{
    private static $has_many = [
        'TagMappings' => TagMapping::class,
    ];
}
```

and configured as:
```

---
Name: tags
---
ObjectA
  extensions:
    - GenericTaggingDataExtension
ObjectA:
  extensions:
    - GenericTaggingDataExtension

```
In CMS UI for editing ObjectA and ObjectB, and error is thrown, similar to:

> [Emergency] Uncaught SilverStripe\ORM\Connect\DatabaseException: Couldn't run query: SELECT DISTINCT "TagMapping"."ClassName", "TagMapping"."LastEdited", "TagMapping"."Created", "TagMapping"."Version", "TagMapping"."Sort", "TagMapping"."JointObjectID", "TagMapping"."OwnerObjectID", "TagMapping"."OwnerObjectClass", "TagMapping"."ID", CASE WHEN "TagMapping"."ClassName" IS NOT NULL THEN "TagMapping"."ClassName" ELSE 'TagMapping' END AS "RecordClassName" FROM "TagMapping" WHERE ("TagMapping"."JointObjectID" IN (?)) AND ("OwnerObject" = ?) ORDER BY "TagMapping"."Sort" ASC Unknown column 'OwnerObject' in 'where clause'

The version that we saw the issue is 3.2.1

**Comment by normann** [comment]
If managed to not throwing the Above errors by changing one piece of code in GridFieldOrderableRows::getSortValuesFromManyManyThroughList(), i.e. the Interface is loading fine, then after a reorder operation, another type of error thrown from the response to the "reorder" request

> Validation error: Object is of class 'TabMapping' which doesn't exist - you need to change the ClassName before you can write it

**Comment by dnsl48** [comment]
Resolved by https://github.com/symbiote/silverstripe-gridfieldextensions/pull/296
Should be released with `3.2.3` and `3.3.0`

**Comment by michalkleiner** [comment]
Thanks @dnsl48 — do you think someone could tag and release the new versions?

**Comment by dnsl48** [comment]
Right, looks like we missed it in the last recipe release.
3.2.3 is out now @michalkleiner
