### ISSUE TITLE
New Release Request

### ISSUE THREAD

**Issue by purplespider** [symbiote/silverstripe-gridfieldextensions#297]
Any possibility in getting a new release tagged?

I'd really like to include the new `RepublishLiveRecords` feature on a site. 
(Can't use `dev-master` due to a third-party module specifying `^3.0`)

Thanks!

**Comment by michalkleiner** [comment]
As a temporary workaround, you can push a new tag to your forked repo, specify your fork in composer.json in `repositories` section and use that "new" version that way until one is tagged here.

You can also use an alias, something like `dev-master#abcdef098 as 3.0.1`, specifying exact commit on master branch as a version that should pass other modules' constraints. Works without the commit hash as well but you don't want to receive everything from a branch as it comes in.

**Comment by michalkleiner** [comment]
Obviously an official new release would be the best :)

**Comment by ntd** [comment]
In the meantime there have been a couple of releases. @purplespider can this be closed?

**Comment by purplespider** [comment]
PR #289 still doesn't seem to be included though. It seems it has been merged into `master`, but not the `3` branch?

**Comment by dhensby** [comment]
Those changes will need to be authored as a new PR against 3 otherwise it won't be released until a new major version is out.

**Comment by purplespider** [comment]
Ah ok, that makes sense. Closing.

@micmania1 Would you be able to apply your PR #289 on the `3` branch?
