### ISSUE TITLE
Accessing fields on many_many through relationship joined on a separate DataObject

### ISSUE THREAD

**Issue by elkebe** [symbiote/silverstripe-gridfieldextensions#303]
Take 2 data objects related with a many_many, joined through a third DataObject, eg.

```
class Trip extends DataObject
{
    private static $many_many = [
        "Clients" => [
            'through' => Booking::class,
            'from' => 'Trip',
            'to' => 'Client',
        ]
    ];
}
class Client extends Member
{
    private static $belongs_many_many = [
        'Trips' => Trip::class,
    ];
}
class Booking extends DataObject
{
    private static $db = [
        'Status' => 'Enum("unconfirmed,confirmed","unconfirmed")',
    ];

    private static $has_one = [
        'Trip' => Trip::class,
        'Client' => Client::class,
    ];
}
```
Clients GridField (in the Trip Details form in CMS) is set up with editable columns. In order to access values in the Booking.Status field, it is possible to use the following:
```
$displayfields = [
		'Join.Status' => [
			'title' => 'Booking Status',
			'callback' => function($record, $column, $grid) {
				return DropdownField::create($column)
                    ->setSource(Booking::get()->DBObject('Status')->enumValues());
			}
		]
    ];
```
However, this field displays as a readonly field and not a dropdown field (same happens for TextField etc.) ie. the file is simply not editable. All other fields such as Client.Name etc. work fine. Not sure whether I'm missing something in the documentation here or whether this is actually a bug...

**Comment by ntd** [comment]
I think you are hitting the same problem I met in #309. I did not find your issue before because I looked for the `GridFieldEditableColumns` search term, sorry for the duplicate.

In PR #311 I provided a way to work with `ManyManyThroughList`. In this case though, you need to use `'Status'` (instead of `'Join.Status'`) because dots in field names break the look up logic, converting every field to a `ReadonlyField`, i.e. the issue you are experiencing.

To be able to use it right now, I added the following code to my `composer.json`:
```json
  "repositories": [
    {
      "type": "git",
      "url": "https://github.com/ntd/silverstripe-gridfieldextensions.git"
    }
  ],
  "require": {
    ...
    "symbiote/silverstripe-gridfieldextensions": "dev-editablecolumns-and-throughlist"
  }
```

**Comment by ntd** [comment]
The recently released [SilverStripe 4.9.0](https://docs.silverstripe.org/en/4/changelogs/4.9.0/) included out of the box support for nested data (see silverstripe/silverstripe-framework#9192). @elkebe are you still around to check if that fixes your problem?

**Comment by elkebe** [comment]
Yes am still around, but not able to work on this at the moment. Will look into this in a couple of weeks. 

E.

**Comment by GuySartorelli** [comment]
Due to the lack of response, I'm going to go with the assumption that https://github.com/symbiote/silverstripe-gridfieldextensions/issues/303#issuecomment-950169169 does indeed fix the problem.
