### ISSUE TITLE
GridFieldEditableColumns with callbacks hides column values on records without edit permissions

### ISSUE THREAD

**Issue by chillu** [symbiote/silverstripe-gridfieldextensions#312]
When using callbacks in `setDisplayFields()`, they work differently than in the parent implementation: It expects a `FormField` instance, rather than a scalar value. `GridFieldEditableColumns ->getColumnContent()` defers to the parent implementation when a record isn't editable, which makes sense. But that parent implementation also evaluates the callback in `setDisplayFields()`, and doesn't know what to do with a form field instance.

```php
<?php
(new GridFieldEditableColumns())
    ->setDisplayFields([
        'Comment' => ['callback' => function ($record, $column, $grid) {
            // return some form field, not a scalar value
        }]);
```

 * Option A: Name the `callback` differently (e.g. `callback_formfields`) to avoid the confusion about the different return values. You could implement this in a backwards compatible way by falling back to `callback`
 * Option B: Don't defer to parent implementation, but rather go through the form field creation logic, and then call `performReadonlyTransformation()` on it before returning

**Comment by robbieaverill** [comment]
Fixed in #314 - thanks @sminnee!
