### ISSUE TITLE
Button appears  when using GridFieldEditableColumns()

### ISSUE THREAD

**Issue by seppzzz** [symbiote/silverstripe-gridfieldextensions#317]
SS 4.6 
When using GridFieldEditableColumns() 
a Header - Button appears in that editable col (see Image- > red circle).
Also if you remove the component GridFieldSortableHeader.

that's wired  especially if you use GridFieldOrderableRows.
that's no good UX.

![Bildschirmfoto 2021-01-06 um 01 39 19](https://user-images.githubusercontent.com/1069249/103715871-facdb600-4fc1-11eb-8456-6d3628d832ec.jpg)

**Comment by emteknetnz** [comment]
Thanks for your suggestion! Just to let you know we're closing this feature request as GitHub issues are not the best place to discuss potential enhancements.  You can read more about the guide on [contributing issues](https://docs.silverstripe.org/en/4/contributing/issues_and_bugs/#feature-requests) and you are welcome to raise new feature ideas on the [Silverstripe forum](https://forum.silverstripe.org/c/feature-ideas) instead.
