### ISSUE TITLE
Inline Editing / Adding on ModelAdmin

### ISSUE THREAD

**Issue by Zauberfisch** [symbiote/silverstripe-gridfieldextensions#32]
Inline Editing and Adding in ModelAdmin is not possible since model Admin has no save action.

**Comment by Zauberfisch** [comment]
A note, for other looking for a solution on this subject:
A simple work around is to create something like SiteConfig (A Admin that just manages 1 DataObject) and add a GridField to that DataObject. (Doesn't even have to be a relation, GridFields can work with normal DataLists).
Or even simpler, just add the GridField to SiteConfig as an additional Tab.

**Comment by g4b0** [comment]
An inline save button should be useful, I'am in a situation where if it's not possible I have to rewrite all my logic from ModelAdmin to a Page containing a GridFileld, including searchContext. Any hints where to start?
