### ISSUE TITLE
GridFieldEditableColumns: DataExtension - can't pass has_one DataObject properties to callback function

### ISSUE THREAD

**Issue by elkebe** [symbiote/silverstripe-gridfieldextensions#320]
Maybe I'm just missing something here, but when I have editable columns set up on DataObject, I can set values/attributes etc. on editable field with eg. $this->DateTimeStart (see first example below). If I move this code into an extension, I would expect to be able to use $this->owner->DateTimeStart (see second example below) however this gives the error: “Trying to get property ‘DateTimeStart’ of non-object”. How do I correctly pass the info through to the grid field in the extension?

Example 1 - DataObject
`class Event extends DataObject {

private static $has_many = ['VenueBookings' => VenueBooking::class];

public function getCMSFields() {

$fields = parent::getCMSFields();

$fields->addFieldToTab('Root.Venues',
            GridField::create('VenueBookings','Venue Bookings',$this->VenueBookings(), 
            GridFieldConfig_RecordEditor::create()
                ->removeComponentsByType([
                    GridFieldDataColumns::class,
                    GridFieldFilterHeader::class,
                    GridFieldAddNewButton::class,
                    GridField_ActionMenu::class
                ])
                // add editbale columns before edit button, then remove it (so delete button ends up on right)
                ->addComponent($venuesgf_cols = new GridFieldEditableColumns(),GridFieldEditButton::class)
                ->addComponent($add_btn = new GridFieldAddNewInlineButton())
                ->removeComponentsByType([GridFieldEditButton::class])
            )
        );

        $add_btn->setTitle('Assign Venue');

        $venuesgf_displayfields = [
			'VenueID' => [
				'title' => 'Venue',
				'callback' => function($record, $column, $grid) {
					return DropdownField::create($column)
                        ->setSource(Venue::get()->map('ID','Title'))
                        ->setEmptyString('< select venue >');
				}
			],
			'DateStart' => [
				'title' => 'Start',
				'callback' => function($record, $column, $grid) {
                    $field = DateField::create($column);
                    $field->setCalendarConfig([
                        'minDate' => $this->DateTimeStart,
                        'maxDate' => $this->DateTimeEnd
                    ]);
                    return $field;
				}
            ],
            'DateEnd' => [
				'title' => 'End',
				'callback' => function($record, $column, $grid) {
                    $field = DateField::create($column);
                    $field->setCalendarConfig([
                        'minDate' => $this->DateTimeStart,
                        'maxDate' => $this->DateTimeEnd
                    ]);
                    return $field;
				}
            ]
        ];
        
        $venuesgf_cols->setDisplayFields($venuesgf_displayfields);

return $fields;

}

}`

Example 2 - DataExtension
`class VenueBookingsEventExtension extends DataExtension {

public function updateCMSFields(FieldList $fields) {

$fields->addFieldToTab('Root.Venues',
            GridField::create('VenueBookings','Venue Bookings',$this->owner->VenueBookings(), 
            GridFieldConfig_RecordEditor::create()
                ->removeComponentsByType([
                    GridFieldDataColumns::class,
                    GridFieldFilterHeader::class,
                    GridFieldAddNewButton::class,
                    GridField_ActionMenu::class
                ])
                // add editbale columns before edit button, then remove it (so delete button ends up on right)
                ->addComponent($venuesgf_cols = new GridFieldEditableColumns(),GridFieldEditButton::class)
                ->addComponent($add_btn = new GridFieldAddNewInlineButton())
                ->removeComponentsByType([GridFieldEditButton::class])
            )->setDescription('<p class="message" style="margin-top:10px;"><i class="fa fa-info-circle"></i> To reset venue bookings to default, delete all current bookings and save.</p>')
        );

        $add_btn->setTitle('Assign Venue');

        $venuesgf_displayfields = [
			'VenueID' => [
				'title' => 'Venue',
				'callback' => function($record, $column, $grid) {
					return DropdownField::create($column)
                        ->setSource(Venue::get()->map('ID','Title'))
                        ->setEmptyString('< select venue >');
				}
			],
			'DateStart' => [
				'title' => 'Start',
				'callback' => function($record, $column, $grid) {
                    $field = DateField::create($column);
                    $field->setCalendarConfig([
                        'minDate' => $this->owner->DateTimeStart,
                        'maxDate' => $this->owner->DateTimeEnd
                    ]);
                    return $field;
				}
            ],
            'DateEnd' => [
				'title' => 'End',
				'callback' => function($record, $column, $grid) {
                    $field = DateField::create($column);
                    $field->setCalendarConfig([
                        'minDate' => $this->owner->DateTimeStart,
                        'maxDate' => $this->owner->DateTimeEnd
                    ]);
                    return $field;
				}
            ],
			'SpacesRemaining' => [
				'title' => 'Spaces',
				'field' => ReadOnlyField::class
			],
			'OverlappingEventsList' => [
				'title' => 'Overlapping Events',
				'field' => ReadOnlyField::class
			]
        ];
        
        $venuesgf_cols->setDisplayFields($venuesgf_displayfields);

}

}`

**Comment by elkebe** [comment]
The same problem happens when a method is called. Eg.
`'SupervisingGuideID' => [
                'title' => 'Supervisor',
                'callback' => function($record, $column, $grid) {
                    return DropdownField::create($column)
                        // show only guides that hold a required supervisor qual
                        ->setSource($this->getSupervisingGuides()->map('ID','Name'))
                        ->setEmptyString('< assign supervision >');
                }
            ]`
works fine in DataObject, however the following
`'SupervisingGuideID' => [
                'title' => 'Supervisor',
                'callback' => function($record, $column, $grid) {
                    return DropdownField::create($column)
                        // show only guides that hold a required supervisor qual
                        ->setSource($this->owner->getSupervisingGuides()->map('ID','Name'))
                        ->setEmptyString('< assign supervision >');
                }
            ]`
does not work in DataExtension.

**Comment by emteknetnz** [comment]
Hi, thanks for taking the time to post to our issue tracker.

The issue tracker is reserved for reporting bugs and we don't provide support via the issue tracker.

A good place to get support is on the [Silverstripe community slack channel](http://silverstripe.org/slack).

Sorry we can't be of more help and good luck resolving your problem.
