### ISSUE TITLE
SS4 Error : Cannot use SilverStripe\Core\Object as Object because 'Object'

### ISSUE THREAD

**Issue by AmadeoMB** [symbiote/silverstripe-gridfieldextensions#322]
I just installed this library and when I try to /dev/build it, it says "Fatal error: Cannot use SilverStripe\Core\Object as Object because 'Object' is a special class name in C:\wamp64\www\asriutama\gridfieldextensions\src\GridFieldAddNewInlineButton.php on line 6".

Did I just do something wrong?

**Comment by emteknetnz** [comment]
Line 6 in the default branch `3` doesn't mention Object https://github.com/symbiote/silverstripe-gridfieldextensions/blob/3/src/GridFieldAddNewInlineButton.php#L6

What version on Gridfieldextensions do you have installed?

**Comment by AmadeoMB** [comment]
This one `composer require symbiote/silverstripe-gridfieldextensions "^3"`. Should I remove the "^3"? So it'll install the latest version?

**Comment by emteknetnz** [comment]
Normally you shouldn't need the quotes around ^3 - can you run `composer show | grep gridfield` which will read the composer.lock file to see what version was installed?

**Comment by AmadeoMB** [comment]
It says version 3.0.0

**Comment by emteknetnz** [comment]
OK that's pretty odd, it should be 3.2.4

Perhaps try it again with slightly different require syntax (using : instead of ")
`composer require symbiote/silverstripe-gridfieldextensions:^3`

**Comment by AmadeoMB** [comment]
Well, It turns out that the ^3 was the problem. I managed to run `composer require symbiote/silverstripe-gridfieldextensions`, and now I got the 3.2.4 version. It runs dev/build perfectly, BUT I was confused with loading them into my project.
I've tried
`use Silverstripe\Forms\GridField\GridFieldOrderableRows`
`use Symbiote\Forms\GridField\GridFieldOrderableRows`
`use Symbiote\SilverStripe\GridFieldOrderableRows`
and still got no luck.

**Comment by emteknetnz** [comment]
Great to hear you got it to work

I noticed that the readme had poor installation instructions so I've updated that

For usage instructions, please refer to https://github.com/symbiote/silverstripe-gridfieldextensions/blob/3/docs/en/index.md

Since there doesn't appear to be a bug with this module, I'll close this issue
