### ISSUE TITLE
Version 3.3.0 requires Silverstripe Framework version ^4.10 which doesn't exist

### ISSUE THREAD

**Issue by davejtoews** [symbiote/silverstripe-gridfieldextensions#328]
The composer.json reads

```json
"silverstripe/framework": "^4.10"
```

Since 4.10 does not exist, composer resolves this to 4.x-dev, and the end result is unreleased dev commits being installed in a repo that requires 3.3.0

![143610429-5a2fa025-4c56-4185-8cf1-dc7e826faffe](https://user-images.githubusercontent.com/9664035/143621749-2eb4e803-742a-42c0-b3bc-4097381c2136.png)

From the git blame it seems like this is deliberate in order to work with php unit 9, but I don't understand why a "stable" release of this module pushes me into non stable versions of the SilverStripe core. This seems premature.

**Comment by emteknetnz** [comment]
Apologies for this - we recommend setting silverstripe/framework to ~4.9.0 until the stable release of 4.10.0.  For a full explanation please read [this section](https://docs.silverstripe.org/en/4/changelogs/beta/4.10.0-beta1/#unstable-framework) in the 4.10.0-beta1 changelog
