### ISSUE TITLE
`getNestedConfig()` called on the parent but should be called on the child

### ISSUE THREAD

**Issue by GuySartorelli** [symbiote/silverstripe-gridfieldextensions#394]
The current state means that a parent is responsible for its children's nested config. This isn't intuitive. Each class should be responsible for its own nested config (i.e. responsible for determining how to show its own children).

## PRs
- https://github.com/symbiote/silverstripe-gridfieldextensions/pull/393

**Comment by sabina-talipova** [comment]
Issue was solved. Task is completed.

**Comment by GuySartorelli** [comment]
FYI @forsdahl I didn't pick up on this during the initial PR, but when looking at the problems Sabina was hitting getting this set up for behat tests I realised this would be a lot more intuitive.
