### ISSUE TITLE
Nested GridField: Update documentation

### ISSUE THREAD

**Issue by sabina-talipova** [symbiote/silverstripe-gridfieldextensions#397]
## Description
The current Nested GridField documentation does not contain enough information. This causes difficulties when implementing this field into a project.
It is necessary to clarify the current version and provide developers with more detailed information with examples of using Nested GridField with different data structures and relationships.

## PR
- https://github.com/symbiote/silverstripe-gridfieldextensions/pull/400

**Comment by GuySartorelli** [comment]
PR merged
