### ISSUE TITLE
Nested gridifeld forces open the left sidebar

### ISSUE THREAD

**Issue by maxime-rainville** [symbiote/silverstripe-gridfieldextensions#403]
When navigating nested GridFlieds, the left side bar is forced open, even if you set it to collapse.

If you toggle the "fix" option it stays closes.

https://youtu.be/-vPjylr98fQ

## Step to reproduce
- Navigate to a a nested gridfield model admin with at least one entry
- Collapse your side bar without choosing the "fixed" option.
- Expand an entry the gridfield.
 
Expected: The entry is expanded and the sidebar stays collapse.
Actual: The entry is loaded, but the collapse sidebar is expanded.

## Acceptance criteria
- The sidebar stays collapse when drilling down a nested gridfield whether "fixed" is collapse or not.

## PRs
- https://github.com/symbiote/silverstripe-gridfieldextensions/pull/406

**Comment by GuySartorelli** [comment]
PR merged
