### ISSUE TITLE
Feature: add sortorder onbeforewrite in orderablegridfield for Many_Many relations

### ISSUE THREAD

**Issue by NobrainerWeb** [symbiote/silverstripe-gridfieldextensions#52]
As also described in #44 writing a sortorder onbeforesave, is sometimes needed (adding items to bottom of list). In #44 you gave an example of setting an initial sortorder for has_many relations - but i need to do the same for many_many relations.

I tried to have a look at it myself, but to complicated for my skills. 
Had some input from Zauberfisch on irq:
[12:24pm] Zauberfisch: subclass the GridFieldOrderableRows, and overwite the list "getter", and if items in that list have a sort of 0, set it to count + 1
[12:24pm] Zauberfisch: (actually max + 1 again)

**Comment by quinnmerio** [comment]
Did you ever find a solution to this? I have the exact same challenge. Want to have sort defined as soon as new relation is added in many_many.

**Comment by creativeSynergy** [comment]
I could also need one :/

**Comment by MattyBalaam** [comment]
Seems this issue just gets asked again and again, but not answer. e.g. https://github.com/silverstripe-australia/silverstripe-gridfieldextensions/issues/138

**Comment by robbieaverill** [comment]
I think we'll triage this as bug rather than a feature. Closing in favour of #138
