### ISSUE TITLE
Typo in  silverstripe-gridfieldextensions/lang/de_DE.yml

### ISSUE THREAD

**Issue by tillzzz** [symbiote/silverstripe-gridfieldextensions#93]
de_DE:
  GridFieldAddExistingSearchHandler.ss:
    NOITEMS: 'Kein Ergebnis'
    RESULTS: 'Ergebnisse'
  GridFieldExtensions:
    ADD: 'Hinzufügen'
    ADDEXISTING: 'Bestenden Eintrag hinzufügen'  <-------- !!   Bestehenden   !!  ---------->
    SEARCH: 'Suche'
    SELECTTYPETOCREATE: '(Bitte Typ wählen)'

**Comment by robbieaverill** [comment]
Hi @tillzzz - would you like to make a pull request to fix this typo?

**Comment by raissanorth** [comment]
764e5aa fixed the typo.
